catalog/Models/Book.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace catalog.Models  {
    public class Book  {
        public int ID  {get; set;}
        public String Name { get; set; }
        public int Pages { get; set; }
        public String Author { get; set; }
        public String ImageUrl  {get; set;}
        public double Price  {get; set;}
        public int InStock  {get; set;}
    }    
}

catalog/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using catalog.Data;
using catalog.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using ServiceStack.Redis;

namespace catalog.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly BookContext _context;
        private readonly IConfiguration _config;

        public IndexModel(ILogger<IndexModel> logger, IConfiguration config, BookContext context)
        {
            _logger = logger;
            _context = context;
            _config = config;
        }

        public void OnGet()
        {
            var books = new List<Book>();

            try
            {
                books = _context.Books.ToList();
            }
            catch (Exception ex)
            {
                ViewData["Error"] = ex.Message;
                ViewData["books"] = books;
                return;
            }

            // UNCOMMENT AFTER ADDING REDIS
            //Get data about the shopping cart
            var client = GetRedisClient();
            var cartItems = client.GetListCount("cart");
            ViewData["cartNo"] = cartItems;

            ViewData["books"] = books;

        }

        public IActionResult OnPostAddToShoppingCart()
        {
            // UNCOMMECT AFTER ADDING REDIS
            var client = GetRedisClient();
            var bookId = int.Parse(Request.Form["bookId"]);

            if (!client.GetAllItemsFromList("cart").Contains(bookId.ToString()))
            {
                var book = _context.Books.Find(bookId);
                book.InStock--;
                _context.SaveChanges();

                client.AddItemToList("cart", bookId.ToString());
            }

            return RedirectToPage();
        }

        public IActionResult OnPostLoad()
        {
            BookLoader.LoadBooks(_context);
            return RedirectToPage();
        }

        private IRedisClient GetRedisClient()
        {
            var conString = _config.GetValue<String>("Redis:ConnectionString");
            var manager = new RedisManagerPool(conString);
            return manager.GetClient();
        }
    }
}

catalog/Pages/Weather.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using catalog.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace catalog.Pages
{
    public class WeatherModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public WeatherModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }

        public void OnPostWeather()
        {
            var ip = Request.Form["ip"];
            ViewData["ip"] = ip;
            var client = new HttpClient();
            var address = $"http://{ip}/api/weather";
            try
            {
                var resp = client.GetAsync(address).Result;
                ViewData["weather"] = resp.Content.ReadAsStringAsync().Result;
            }
            catch (Exception ex)
            {
                ViewData["error"] = "Error getting weather data: " + ex.Message;
            }
        }
    }
}

catalog/Pages/Index.cshtml
@page

@using Models

@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<img width="40" src="~/images/cart.jpg"/> (@ViewData["cartNo"])
<br/>
<div class="text-center">

    <h1 class="display-5">Our Books:</h1>
    <table class="table">
        <tr>
            <th>Name</th>
            <th>Author</th>
            <th>Pages</th>  
            <th>Price</th>   
            <th></th>       
        </tr>        
    
    @foreach (var book in ViewData["books"] as List<Book>)
    {
        <tr>
            <td>
                @Html.DisplayFor(m=>book.Name)
            </td>
            <td>
                @Html.DisplayFor(m=>book.Author)
            </td>
            <td>
                @Html.DisplayFor(m=>book.Pages)
            </td>
            <td>
                @Html.DisplayFor(m=>book.Price)
            </td>
            <td>
                @if (book.InStock<=0)  {
                    <p>Out of stock :-(</p>
                }
                else  {
                <form asp-page-handler="addToShoppingCart" method="post">
                    <input type="hidden" name="bookId" value="@book.ID"/>
                    <button>Add to shopping cart</button>
                </form>
                }
            </td>
        </tr>        
    }
    </table>
    <form asp-page-handler="load" method="post">
        <button>Load Books to DB</button>
    </form>

    @if (ViewData["Error"]!=null)  {
        <p style='color: red'>@ViewData["Error"]</p>
    }
</div>

catalog/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ReadIt! - catalog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-danger box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index"><img width="100" src="~/images/logo.jpg"/></a>
                <a class="navbar-brand" asp-area="" asp-page="/Index">Home</a>
                <a class="navbar-brand" asp-area="" asp-page="/Weather">Weather</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - ReadIt! 
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

catalog/Pages/Weather.cshtml
@page

@model WeatherModel

<div class="text-center">

    <h1 class="display-5">Our Weather:</h1>
    <form asp-page-handler="weather" method="post">
        Weather Server IP:
        @if (ViewData["ip"] == null)
        {
            <input type="text" name="ip" />
        }
        else
        {
            <input type="text" name="ip" value="@ViewData["ip"]" />
        }

        <button>Get Weather</button>
    </form>
    <br /><br />
    @if (ViewData["weather"] != null)
    {
        <p> @ViewData["weather"] degrees Celsius</p>
    }
    else
    {
        if (ViewData["error"] != null)
        {
            <p style="color: red;">@ViewData["error"]</p>
        }
        else
        {
            <p>No weather data</p>
        }
    }

</div>